// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Project → Before / after*
 */
export interface ProjectDocumentDataBeforeAfterItem {
  /**
   * Before field in *Project → Before / after*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.before_after[].before
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  before: prismic.KeyTextField;

  /**
   * After field in *Project → Before / after*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.before_after[].after
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  after: prismic.KeyTextField;
}

/**
 * Item in *Project → Deliverables*
 */
export interface ProjectDocumentDataDeliverablesItem {
  /**
   * Item field in *Project → Deliverables*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.deliverables[].item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item: prismic.KeyTextField;
}

/**
 * Item in *Project → Highlights*
 */
export interface ProjectDocumentDataHighlightsItem {
  /**
   * Item field in *Project → Highlights*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.highlights[].item
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  item: prismic.KeyTextField;
}

/**
 * Item in *Project → Gallery*
 */
export interface ProjectDocumentDataGalleryItem {
  /**
   * Image field in *Project → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Caption field in *Project → Gallery*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;
}

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Title field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Casa Amarela
   * - **API ID Path**: project.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Year field in *Project*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 2026
   * - **API ID Path**: project.year
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  year: prismic.NumberField;

  /**
   * Location field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Laguna, Cabeçuda, SC, Brasil
   * - **API ID Path**: project.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Category field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Residential
   * - **API ID Path**: project.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Area field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 1400 m²
   * - **API ID Path**: project.area
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  area: prismic.KeyTextField;

  /**
   * Client field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Projeto próprio
   * - **API ID Path**: project.client
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  client: prismic.KeyTextField;

  /**
   * Status field in *Project*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Em fase de projeto
   * - **API ID Path**: project.status
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  status: prismic.KeyTextField;

  /**
   * Accent theme field in *Project*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: stone
   * - **API ID Path**: project.accent_theme
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  accent_theme: prismic.SelectField<
    "stone" | "ivory" | "sand" | "amber",
    "filled"
  >;

  /**
   * Summary field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.summary
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  summary: prismic.RichTextField;

  /**
   * Impact field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.impact
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  impact: prismic.RichTextField;

  /**
   * Intro field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro: prismic.RichTextField;

  /**
   * Challenge field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.challenge
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  challenge: prismic.RichTextField;

  /**
   * Solution field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.solution
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  solution: prismic.RichTextField;

  /**
   * Result field in *Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.result
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  result: prismic.RichTextField;

  /**
   * Before / after field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.before_after[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  before_after: prismic.GroupField<
    Simplify<ProjectDocumentDataBeforeAfterItem>
  >;

  /**
   * Deliverables field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.deliverables[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  deliverables: prismic.GroupField<
    Simplify<ProjectDocumentDataDeliverablesItem>
  >;

  /**
   * Highlights field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.highlights[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  highlights: prismic.GroupField<Simplify<ProjectDocumentDataHighlightsItem>>;

  /**
   * Gallery field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.gallery[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery: prismic.GroupField<Simplify<ProjectDocumentDataGalleryItem>>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Item in *Settings → Intro rows*
 */
export interface SettingsDocumentDataIntroRowsItem {
  /**
   * Foco field in *Settings → Intro rows*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.intro_rows[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Interiores residenciais/comerciais field in *Settings → Intro rows*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Interiores residenciais e comerciais
   * - **API ID Path**: settings.intro_rows[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Item in *Settings → About paragraphs*
 */
export interface SettingsDocumentDataAboutParagraphsItem {
  /**
   * Text field in *Settings → About paragraphs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.about_paragraphs[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * About Paragrafo1 field in *Settings → About paragraphs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Leitura cuidada do espaço, da proporção e da atmosfera que cada projeto precisa de transmitir.
   * - **API ID Path**: settings.about_paragraphs[].about_paragrafo1
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_paragrafo1: prismic.KeyTextField;
}

/**
 * Item in *Settings → Services items*
 */
export interface SettingsDocumentDataServicesItemsItem {
  /**
   * Title field in *Settings → Services items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.services_items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Settings → Services items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.services_items[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Item in *Settings → Process steps*
 */
export interface SettingsDocumentDataProcessStepsItem {
  /**
   * Number field in *Settings → Process steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.process_steps[].number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  number: prismic.KeyTextField;

  /**
   * Title field in *Settings → Process steps*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.process_steps[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Settings → Process steps*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.process_steps[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Item in *Settings → About page body*
 */
export interface SettingsDocumentDataAboutPageBodyItem {
  /**
   * Text field in *Settings → About page body*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.about_page_body[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Item in *Settings → About page stats*
 */
export interface SettingsDocumentDataAboutPageStatsItem {
  /**
   * Label field in *Settings → About page stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.about_page_stats[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *Settings → About page stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.about_page_stats[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Item in *Settings → Services page sections*
 */
export interface SettingsDocumentDataServicesPageSectionsItem {
  /**
   * Title field in *Settings → Services page sections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.services_page_sections[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *Settings → Services page sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.services_page_sections[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Francisco Beça Múrias | Portfolio field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Francisco Beça Múrias | Interior Design Portfolio
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Portfolio bilingue, desenho 2D e 3D field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Portfolio bilingue de design de interiores, desenho 2D e 3D com linguagem minimalista e elegante.
   * - **API ID Path**: settings.site_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  site_description: prismic.RichTextField;

  /**
   * OG title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_title: prismic.KeyTextField;

  /**
   * OG description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.og_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  og_description: prismic.RichTextField;

  /**
   * Francisco Beça Múrias field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Francisco Beça Múrias
   * - **API ID Path**: settings.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Design de interiores · 2D · 3D field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Design de interiores · 2D · 3D
   * - **API ID Path**: settings.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Interior designer · 2D · 3D field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Interior designer · 2D drafting · 3D visualization
   * - **API ID Path**: settings.hero_eyebrow
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_eyebrow: prismic.KeyTextField;

  /**
   * Designer de interiores e ambientes. field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Designer de interiores com leitura espacial 2D e 3D construídas com precisão.
   * - **API ID Path**: settings.hero_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_description: prismic.RichTextField;

  /**
   * projetos residenciais, hospitality. field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Disponível para projetos residenciais, hospitality e colaboração criativa.
   * - **API ID Path**: settings.hero_note
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_note: prismic.RichTextField;

  /**
   * Intro rows field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.intro_rows[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  intro_rows: prismic.GroupField<Simplify<SettingsDocumentDataIntroRowsItem>>;

  /**
   * About field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Interiores, desenho técnico e visualização com uma linguagem contida e precisa.
   * - **API ID Path**: settings.about_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_title: prismic.KeyTextField;

  /**
   * About paragraphs field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.about_paragraphs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  about_paragraphs: prismic.GroupField<
    Simplify<SettingsDocumentDataAboutParagraphsItem>
  >;

  /**
   * Projects title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.projects_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  projects_title: prismic.KeyTextField;

  /**
   * Projects description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.projects_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  projects_description: prismic.RichTextField;

  /**
   * Services title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.services_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  services_title: prismic.KeyTextField;

  /**
   * Services description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.services_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  services_description: prismic.RichTextField;

  /**
   * Services items field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.services_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services_items: prismic.GroupField<
    Simplify<SettingsDocumentDataServicesItemsItem>
  >;

  /**
   * Process title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.process_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  process_title: prismic.KeyTextField;

  /**
   * Process description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.process_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  process_description: prismic.RichTextField;

  /**
   * Process steps field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.process_steps[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  process_steps: prismic.GroupField<
    Simplify<SettingsDocumentDataProcessStepsItem>
  >;

  /**
   * Contact title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_title: prismic.KeyTextField;

  /**
   * Contact description field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.contact_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact_description: prismic.RichTextField;

  /**
   * About page title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.about_page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  about_page_title: prismic.KeyTextField;

  /**
   * About page intro field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.about_page_intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  about_page_intro: prismic.RichTextField;

  /**
   * About page body field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.about_page_body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  about_page_body: prismic.GroupField<
    Simplify<SettingsDocumentDataAboutPageBodyItem>
  >;

  /**
   * About page stats field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.about_page_stats[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  about_page_stats: prismic.GroupField<
    Simplify<SettingsDocumentDataAboutPageStatsItem>
  >;

  /**
   * Services page title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.services_page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  services_page_title: prismic.KeyTextField;

  /**
   * Services page intro field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.services_page_intro
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  services_page_intro: prismic.RichTextField;

  /**
   * Services page sections field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.services_page_sections[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services_page_sections: prismic.GroupField<
    Simplify<SettingsDocumentDataServicesPageSectionsItem>
  >;

  /**
   * Footer field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  footer: prismic.KeyTextField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = ProjectDocument | SettingsDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataBeforeAfterItem,
      ProjectDocumentDataDeliverablesItem,
      ProjectDocumentDataHighlightsItem,
      ProjectDocumentDataGalleryItem,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataIntroRowsItem,
      SettingsDocumentDataAboutParagraphsItem,
      SettingsDocumentDataServicesItemsItem,
      SettingsDocumentDataProcessStepsItem,
      SettingsDocumentDataAboutPageBodyItem,
      SettingsDocumentDataAboutPageStatsItem,
      SettingsDocumentDataServicesPageSectionsItem,
      AllDocumentTypes,
    };
  }
}
